word_list = [
    "яблоко",  # apple
    "банан",  # banana
    "машина",  # car
    "собака",  # dog
    "слон",  # elephant
    "цветок",  # flower
    "гитара",  # guitar
    "дом",  # house
    "лёд",  # ice
    "куртка",  # jacket
    "воздушный змей",  # kite
    "лампа",  # lamp
    "гора",  # mountain
    "тетрадь",  # notebook
    "океан",  # ocean
    "пицца",  # pizza
    "королева",  # queen
    "река",  # river
    "солнце",  # sun
    "дерево",  # tree
    "зонтик",  # umbrella
    "скрипка",  # violin
    "кит",  # whale
    "ксилофон",  # xylophone
    "яхта",  # yacht
    "зебра",  # zebra
    "самолет",  # airplane
    "воздушный шар",  # balloon
    "камера",  # camera
    "стол",  # desk
    "двигатель",  # engine
    "лес",  # forest
    "сад",  # garden
    "вертолет",  # helicopter
    "остров",  # island
    "джунгли",  # jungle
    "кенгуру",  # kangaroo
    "лестница",  # ladder
    "магнит",  # magnet
    "игла",  # needle
    "сад",  # orchard
    "карандаш",  # pencil
    "одеяло",  # quilt
    "радуга",  # rainbow
    "парусник",  # sailboat
    "телефон",  # telephone
    "единорог",  # unicorn
    "ваза",  # vase
    "окно",  # window
    "рентген",  # x-ray
    "йогурт",  # yogurt
    "зоопарк",  # zoo
    "корзина",  # basket
    "свеча",  # candle
    "дверь",  # door
    "конверт",  # envelope
    "фонтан",  # fountain
    "перчатка",  # glove
    "молоток",  # hammer
    "насекомое",  # insect
    "драгоценность",  # jewel
    "ключ",  # key
    "лимон",  # lemon
    "зеркало",  # mirror
    "ожерелье",  # necklace
    "устрица",  # oyster
    "картина",  # painting
    "зыбучие пески",  # quicksand
    "ракета",  # rocket
    "снежинка",  # snowflake
    "телескоп",  # telescope
    "нижнее белье",  # underwear
    "гриф",  # vulture
    "часы",  # watch
    "ксерокс",  # xerox
    "пряжа",  # yarn
    "молния",  # zipper
    "хлеб",  # bread
    "кот",  # cat
    "барабан",  # drum
    "яйцо",  # egg
    "рыба",  # fish
    "виноград",  # grape
    "шляпа",  # hat
    "иглу",  # igloo
    "пальто",  # jacket
    "змей",  # kite
    "лев",  # lion
    "луна",  # moon
    "гнездо",  # nest
    "осьминог",  # octopus
    "груша",  # pear
    "перепел",  # quail
    "робот",  # robot
    "звезда",  # star
    "поезд",  # train
    "униформа",  # uniform
    "вакцина",  # vaccine
    "водопад",  # waterfall
    "зевота",  # yawn
    "зефир"  # zephyr
]